# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('default', '0008_classlisting_coreqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreePlanTemplate',
            fields=[
                ('Major', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Credits', models.IntegerField()),
                ('Semester1', models.TextField(default='NONE')),
                ('Semester2', models.TextField(default='NONE')),
                ('Semester3', models.TextField(default='NONE')),
                ('Semester4', models.TextField(default='NONE')),
                ('Semester5', models.TextField(default='NONE')),
                ('Semester6', models.TextField(default='NONE')),
                ('Semester7', models.TextField(default='NONE')),
                ('Semester8', models.TextField(default='NONE')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDegreePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Major', models.CharField(max_length=30)),
                ('Entry', models.CharField(choices=[('F', 'Fall'), ('S', 'Spring')], default='F"', max_length=1)),
                ('CreditsRemaining', models.IntegerField()),
                ('Semesters', models.TextField()),
                ('LinkedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(null=True)),
                ('Term', models.CharField(choices=[('F', 'Fall'), ('S', 'Spring'), ('SS', 'Summer')], max_length=2)),
                ('Classes', models.TextField(null=True)),
                ('Credits', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester1',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester2',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester3',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester4',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester5',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester6',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester7',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester8',
        ),
        migrations.DeleteModel(
            name='DegreePlan',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
